# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mark', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name_plural': 'Ведомости',
                'db_table': 'mark_lists',
                'verbose_name': 'Ведомость',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('birth', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Студенты',
                'db_table': 'students',
                'verbose_name': 'Студент',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name_plural': 'Предметы',
                'db_table': 'subjects',
                'verbose_name': 'Предмет',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('ex', models.IntegerField(verbose_name='Опыт')),
                ('department', models.CharField(max_length=255, verbose_name='Кафедра')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='core.Subject')),
            ],
            options={
                'verbose_name_plural': 'Преподаватели',
                'db_table': 'teachers',
                'verbose_name': 'Преподаватель',
            },
        ),
        migrations.AddField(
            model_name='marklist',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.Student'),
        ),
        migrations.AddField(
            model_name='marklist',
            name='subject',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='core.Subject'),
        ),
        migrations.AddField(
            model_name='marklist',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='core.Teacher'),
        ),
    ]
