# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
                'db_table': 'departments',
            },
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(db_column='department_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Department'),
        ),
    ]
