# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160604_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marklist',
            name='subject',
        ),
        migrations.AlterField(
            model_name='marklist',
            name='mark',
            field=models.CharField(max_length=255, verbose_name='Оценка'),
        ),
    ]
