# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160604_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Тип')),
            ],
            options={
                'db_table': 'c_types',
                'verbose_name': 'Тип контроля',
                'verbose_name_plural': 'Типы контроля',
            },
        ),
        migrations.AddField(
            model_name='marklist',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='marklist',
            name='c_type',
            field=models.ForeignKey(db_column='c_type_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ControlType'),
        ),
    ]
